#!/usr/bin/env python3
import sys
# print(sys.argv)
if len(sys.argv) != 2:
    info_str = """
	command to execute:
		llist "<path>/<glob_pattern>"
    """
    print(info_str)
    sys.exit(1)
    
import glob
import os

for i in glob.glob(sys.argv[1]):
    print(i)
